name: Run Tests, Format and Check code, and Coverage

on: [push, pull_request]

jobs:
  tests_coverage_and_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install pytest coverage pre-commit

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Run tests and enforce 100% coverage
        run: |
          coverage run -m pytest
                coverage report --fail-under=100
      - name: Check if tests and coverage passed
        run: echo "🎉 Clean code, tests, and coverage confirmed!"
